// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.0
// source: signalling.proto

package signalling

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SignallingServiceClient is the client API for SignallingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SignallingServiceClient interface {
	Ping(ctx context.Context, in *PingMsg, opts ...grpc.CallOption) (*PongMsg, error)
}

type signallingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSignallingServiceClient(cc grpc.ClientConnInterface) SignallingServiceClient {
	return &signallingServiceClient{cc}
}

func (c *signallingServiceClient) Ping(ctx context.Context, in *PingMsg, opts ...grpc.CallOption) (*PongMsg, error) {
	out := new(PongMsg)
	err := c.cc.Invoke(ctx, "/SignallingService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignallingServiceServer is the server API for SignallingService service.
// All implementations must embed UnimplementedSignallingServiceServer
// for forward compatibility
type SignallingServiceServer interface {
	Ping(context.Context, *PingMsg) (*PongMsg, error)
	mustEmbedUnimplementedSignallingServiceServer()
}

// UnimplementedSignallingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSignallingServiceServer struct {
}

func (UnimplementedSignallingServiceServer) Ping(context.Context, *PingMsg) (*PongMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedSignallingServiceServer) mustEmbedUnimplementedSignallingServiceServer() {}

// UnsafeSignallingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignallingServiceServer will
// result in compilation errors.
type UnsafeSignallingServiceServer interface {
	mustEmbedUnimplementedSignallingServiceServer()
}

func RegisterSignallingServiceServer(s grpc.ServiceRegistrar, srv SignallingServiceServer) {
	s.RegisterService(&SignallingService_ServiceDesc, srv)
}

func _SignallingService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignallingServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SignallingService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignallingServiceServer).Ping(ctx, req.(*PingMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// SignallingService_ServiceDesc is the grpc.ServiceDesc for SignallingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SignallingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SignallingService",
	HandlerType: (*SignallingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _SignallingService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "signalling.proto",
}
